Hallo
canpie/CANpie pull request #3
Opened 2017-01-25 11:38 UTC by BergerMicroControl

Ich hab mal  hallo  reingeschrieben bitte mal in die main übernehmen

2017-01-25 11:43 UTC, microcontrol22 requested changes
Branching works - go on.

2017-01-30 11:15 UTC, BergerMicroControl commented
implementation of the test cases from the specification.

2017-02-01 14:27 UTC, microcontrol22 requested changes
Coding style issues detected. In addition, the data type of the function return value are not compared properly.

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +   CpMsgSetDlc(&tsCanMsgS, 0x56);
This makes no sense, because value is invalid. Test case needs to be revised.

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +** \file    test_cp_msg_ccf.c
Code style has to be observed:
** \file    test_cp_msg_ccf.c
** \brief   Test cases for message access functions
**
** The following test cases cover the CANpie FD message API. They are
** described inside the CANpie FD test specification and marked as
** CP_MSG_CCF_<num>.
** <p>

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +   TEST_ASSERT_EQUAL_UINT32(0, CpMsgGetDlc(&tsCanMsgS));
Return value is UINT8

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +   TEST_ASSERT_EQUAL_UINT32(0, CpMsgGetData(&tsCanMsgS,1));
Return value is UINT8

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +   TEST_ASSERT_EQUAL_UINT32(0,CpMsgGetDlc(&tsCanMsgS));
Return value is UINT8

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +      TEST_ASSERT_EQUAL_UINT32(uwCountS, CpMsgGetStdId(&tsCanMsgS));
Return value is UINT16

2017-02-01 14:27 UTC, microcontrol22 commented on source/tests/canpie-fd/test_cp_msg_ccf.c
> +      TEST_ASSERT_EQUAL_UINT32(uwCountS & CP_MASK_STD_FRAME, CpMsgGetStdId(&tsCanMsgS));
Return value is UINT16

2017-02-09 14:24 UTC, microcontrol22 commented
No change because of merge conflicts.

2017-02-09 14:24 UTC, closed without merging